### ISSUE TITLE
Player can interact with items by typing certain commands

### ISSUE THREAD

**Issue by ozyx** [SaddlebackCSS/spring-break-text-adventure#11]
These should be alluded to in the room description.

**Comment by TheFirstLairron** [comment]
Are we going to be checking for a specific phrase like "Examine the vase" or are we just looking for the mention of an item's name? if the latter, i have an idea for how to handle it

**Comment by ozyx** [comment]
I was thinking the player could just type the item name. For simplicity. Would love to hear your ideas

**Comment by TheFirstLairron** [comment]
We could just use the built in instr () method on their input. If it returns a position, act on it.

**Comment by ozyx** [comment]
Instr ()? Is that a string method? I was thinking each room would have a list of keywords we would iterate thru each time the player sent a command that wasn't a cardinal direction.

**Comment by TheFirstLairron** [comment]
Yeah, it is, and we could actually do a bit of both. For each of the keywords, check if the word is contained within the string. I will put together a demo tonight.

**Comment by TheFirstLairron** [comment]
I just realized, its string.find() not instr(). I might be mixing up languages

**Comment by TheFirstLairron** [comment]
There is a demo of what i was talking about in a branch. Go ahead and check it out when you get the chance

**Comment by ozyx** [comment]
Haha. It happens.
So what I've worked out so far is that each room is an object, containing all of the information pertinent to that room and its surroundings.

I think we should use maps to connect rooms. A map is basically a data structure that holds a key and a value. The key is what you use to retrieve the value. So in this case, each room would have 4 string variables: 

```
std::string north;
std::string south;
std::string east;
std::string west;
```

These would hold the key to another room, so the game loop would then retrieve the new room from the map and set the player's current location to it.

We can use keywords like this. Each Room object can have a keyword variable or a list of keywords that when typed, the map can retrieve another Room or an Event.
I don't know if that made any sense. These are just my ideas. I figure we can design the back-end in such a fashion that it makes it easier for others to contribute (i.e. add room descriptions, keywords and stuff to a text file which we will use to read in the initial data)

checking out your branch now

**Comment by ozyx** [comment]
.find() omfg i didn't even know that existed
that's amazing

**Comment by TheFirstLairron** [comment]
It's beautiful huh? It's one of those things that if a language I'm messing with doesn't have a function like that, I will for sure be writing one really quick.

**Comment by ozyx** [comment]
Yes I think we are definitely going to be using find().

**Comment by ozyx** [comment]
Closing.
