### ISSUE TITLE
Our game needs win and lose conditions

### ISSUE THREAD

**Issue by ozyx** [SaddlebackCSS/spring-break-text-adventure#12]
List all of your fun ideas on events which end the game. These can be positive or negative.

**Comment by ainix** [comment]
Could it be room-escape themed? Like, in the game, you could either find your way out of the spooky mansion by following hints of directions or discover some skeleton in the closet and blackmail the host to let you go.

**Comment by ozyx** [comment]
Hahahaha!! Yeah!! That would be awesome. We could have multiple win conditions, that wouldn't be hard to implement at all. We would start detailing this stuff while/after we complete #6 . I like the blackmail the host idea.

**Comment by rpadilla6** [comment]
We could throw in a few lose conditions as well, with rooms leading to death or something crazy like walking in on yourself sleeping and the whole thing was just a lucid dream.

**Comment by Autofire** [comment]
So, I guess we won't have an HP system. Maybe we could have some other system...maybe hunger? Like, the player has to keep exploring and find food or else they'll starve.

**Comment by ozyx** [comment]
Closing.
