### ISSUE TITLE
Inventory System

### ISSUE THREAD

**Issue by TheFirstLairron** [SaddlebackCSS/spring-break-text-adventure#15]
Do we need an inventory system? Because I can make one.

**Comment by ozyx** [comment]
Probably not unless it would be easy to implement, right now we should focus on creating a map and having the player navigate through it. that's step 1. step two would be implementing interactive keywords (other than north south east west) that vary by room. the next step could be an inventory system if it's not hard to get running.

**Comment by TheFirstLairron** [comment]
I don't believe It would be. Especially if we know all the items beforehand. Well, just saying I would like to work on it when it comes to it.

**Comment by ozyx** [comment]
i'm all for it

**Comment by TheFirstLairron** [comment]
I think I'm gonna do this in the next day or so, seems like we are getting towards the point where we should have it fleshed out.

**Comment by ozyx** [comment]
Closing.
