### ISSUE TITLE
We need a way to initialize our map by reading from a text file

### ISSUE THREAD

**Issue by ozyx** [SaddlebackCSS/spring-break-text-adventure#21]
Program will read a big text file which creates and initializes all rooms. Format of the text file must be defined and preferably endline delimited. Something like:

```
Room Key
description
North Key
West Key
South Key
East Key
Number of items to follow
item 1
description
item 2...
description
item n
description
```

**Comment by ozyx** [comment]
@SaddlebackCSS/springbreak-text-team 
Just letting you guys know, once me and @TheFirstLairron get this issue settled we can let you know how to format your room descriptions. We are going to try and come up with some way that will make it easy for everyone to contribute. 
Start mapping and writing your room descriptions and we will keep you posted on the progress of this issue. We're meeting up tomorrow to work on the back-end.

**Comment by ainix** [comment]
Sounds good!

**Comment by ozyx** [comment]
Closing.
