### ISSUE TITLE
We need a handy word-wrap function for formatting our description outputs(sitting in develop, ready to be tested)

### ISSUE THREAD

**Issue by ozyx** [SaddlebackCSS/spring-break-text-adventure#3]
function should take in a string and an integer length, and wrap the words to that length, make sure it doesn't cut off any words.

**Comment by TheFirstLairron** [comment]
I can take this on.

**Comment by ozyx** [comment]
branch from master, create your new branch with the naming scheme `[issue id]-brief-description` and you're good to go. make sure your commits have the issue id in them as well. I like to prepend commits with them like this: "[#3] here is my commit message"

**Comment by ozyx** [comment]
branch from develop, actually

**Comment by TheFirstLairron** [comment]
Sitting in develop, ready to be tested and eventually pulled to master
