### ISSUE TITLE
We need to map out the rooms.

### ISSUE THREAD

**Issue by ozyx** [SaddlebackCSS/spring-break-text-adventure#6]
We can do this on LucidChart, which is a collaborative white-board that we can all use simultaneously. We can even chat with eachother on there. I made a [document for the map.](https://www.lucidchart.com/invitations/accept/a51e936c-672e-48c9-a0ae-6f61005c8600)

**Comment by TheFirstLairron** [comment]
Maybe we should try and meet in person to discuss this a little before we start actually designing?

**Comment by ainix** [comment]
I agree. A lot of details are still unclear.

**Comment by ozyx** [comment]
Quite frankly I don't have enough time to set up a meeting unless it was over spring break. But that's why I pieced it out into tasks. We are doing a mini "scrum" method of development. The general process goes like this:

Tasks are set up so that devs can work autonomously. 
One person comes up with a rough draft, all others review it, if it doesn't work it is revised, go back to step 1. 

At this point it's just a matter of drawing a house Plan with rooms. Step by step.

**Comment by TheFirstLairron** [comment]
Alright, i will try and do some work on the layout in the next few days.

**Comment by ozyx** [comment]
If you want I can set us up a slack board which is basically like a shared chatroom where we can chat in real time, share pics, etc. Lemme know.

**Comment by TheFirstLairron** [comment]
That sounds like it would be very helpful, and if you dont have the time, i can try and set it up.

**Comment by ozyx** [comment]
the website is slack.com, it's really easy to set up. You might need everyone's emails though. The slack phone app is fantastic as well. I'm using it with two other projects right now.

**Comment by TheFirstLairron** [comment]
I just created one, just get me your email everyone and i will add you

**Comment by ozyx** [comment]
jessemazzella@gmail.com

**Comment by TheFirstLairron** [comment]
i added you jesse

**Comment by ainix** [comment]
aini.xu@yahoo.com
Let me know.

**Comment by ozyx** [comment]
@ainix I invited you to our Slack site. It's a pretty cool website, really fun to use and it's also used in the professional world. It's basically a customizable IRC chatroom with emojis that integrates with GitHub.

**Comment by ghost** [comment]
add me too, mayamorok@gmail.com

**Comment by TheFirstLairron** [comment]
@o5akafeeva added

**Comment by ozyx** [comment]
Closing.
